CREATE TABLE IF NOT EXISTS contacts (
    phone VARCHAR(50) PRIMARY KEY,
    jid VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
